<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <!-- 1.1 Give your groupId, artifactId, and version -->
  <groupId>com.StudyCafe_R</groupId>
  <artifactId>StudyCafe_Server_For_React</artifactId>
  <version>1.0</version>
  <packaging>pom</packaging>

  <!-- 1.2 List modules in the order you want them built -->
  <modules>
    <!-- Make sure domain comes before infrastructure -->
    <module>StudyCafeDomain</module>
    <module>InfraStructure</module>
  </modules>

  <!-- 1.3 Optionally you can declare common properties/dependencyManagement here -->

</project>