version: "3"

services:
  mysql-test:
    image: mysql:8.0
    container_name: mysql-test
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/data/mysql:/var/lib/mysql
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping"] 
#       interval: 10s
#       timeout: 5s
#       retries: 5

  redis-test:
    image: "redis:alpine"
    container_name: redis-test
    ports:
      - "6379:6379"
    volumes:
      - ~/data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-app:
    image: kuuku123/studycafe_server_for_react:latest
    depends_on:
      - mysql-test
      - redis-test
    ports:
      - "8081:8081"
    entrypoint: ["java", "-jar", "-Djasypt.encryptor.password=my_jasypt_key", "-Dspring.profiles.active=prod", "/app/StudyCafe_Server_For_React-1.0.jar"]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 10
        window: 60s
