spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(6MOcv4Th3t0UbkxQ1FSpKGau/NcO4tM0Z9un8rCPfxvd/zNZkaIht3edok+23Dk5jtVQBJ7GCiYRhfXSNN647EHmJISv1TvBRfPagmzRp2OU0U1D1xFsnQ==)
    username: ENC(40DEax6Zheq0RZkYLlznAQ==)
    password: ENC(IvkhaAGOkTdaJfluLQGMEA==)
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(Ury0e1TSqFOpO73mRr+Ds1otgbsymbxfw4zY3vUQkKU=)
    password: ENC(eeL/0j6MAjVPG63SjYhmrWDNLZgHt5SKN+MF9yJeX4g=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 742031203215-3ki2goqrmvc6qh6gpe6c6js3d5ve39qu.apps.googleusercontent.com
            client-secret: ENC(peUYU35cbfi4UxhQjHvS7jJAIWdJ62XzoZ6XnYOSatkKFa4iiYFFoa/q6ur4aqYt)
            scope: email,profile


cors:
  allowed-origin: http://tonylimtest123.duckdns.org #duckdns

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
server:
  port: 8081
  servlet:
    session:
      cookie:
        http-only: false
        name: StudyCafe_Session_Cookie
      timeout: 30m
  session:
    store-type: redis

  redis:
    host: redis-test
    port: 6379

app:
  host: http://tonylimtest123.duckdns.org:8081
