spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(nBbb+njXtjlneIFew/UFNq78q/2iIuvH3kFKaX4gqowaDj9gH4pPMiN3Jfj+ZlEIpUX8KtriuavFfPuCoaLzVPmU0L+cWqcnAjkEMfO/pImE318lXsqDcA==)
    username: ENC(PM6hzMZxoQxfeMYEjlqe9Q==)
    password: ENC(k+QRlojJ5PRJcIcwoBZGhA==)
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(GXEU5MhA5rAmRzD9eeJVQgjiNwB7mSTLiIqkb8D90OA=)
    password: ENC(FzUlexyhDLQSdAvxlkPSDdjqQdP1E23Fst6/6rrstIk=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: false
logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
server:
  port: 8081
  servlet:
    session:
      cookie:
        http-only: false
        max-age:
        name: StudyCafe_Session_Cookie